---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-mlops-profile
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-mlops-profile
  validation: client

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: test-mlops-profile
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: weave-gitops-ekz-ekz-test-mlops-profile
  url: ssh://git@github.com/chanwit/test-mlops-profile.git

