apiVersion: weave.works/v1alpha1
kind: ProfileInstallation
metadata:
  creationTimestamp: null
  name: pctl-profile
  namespace: default
spec:
  source:
    branch: main
    path: mlops
    url: https://github.com/chanwit/mlops-profile
status: {}
