apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: mlops-profile-mlops-kfp-cluster-scoped
  namespace: profiles-system
spec:
  interval: 5m0s
  path: artifacts/kfp-cluster-scoped/kfp-cluster-scoped
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: profiles-system
status: {}
