apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-mlops-kfp
  namespace: default
spec:
  interval: 5m0s
  path: artifacts/kfp/kfp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
status: {}
